### ISSUE TITLE
infografia-lenguajes-de-programacion

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Abraham890#1]
[infografia_Abraham_Reyes_Oriz.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Abraham890/files/8567878/infografia_Abraham_Reyes_Oriz.pdf)

**Comment by christopheremv** [comment]
calificación:  19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
